/*
SLEZIONA TUTTI I CAMPI DI TUTTI I COSTUMI CHE ABBIANO UN COSTO
SUPERIORE AI 500€ E LI ORDINA IN ORDINE CRESCENTE DI COSTO
*/

USE acme_societa;

SELECT *
FROM costume
WHERE costo>=500
ORDER BY costo;